version: "3.4"

services:
  app:
    depends_on:
      - database
    environment:
      - POSTGRES_DB=bellerophon
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./src:/app/src
  database:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=bellerophon
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: {}
